name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar pruebas y generar reporte
        run: python -m unittest -v 2>&1 | tee reporte-pruebas.txt

      - name: Guardar el reporte
        uses: actions/upload-artifact@v4
        with:
          name: reporte-pruebas
          path: reporte-pruebas.txt